### ISSUE TITLE
Precompile a release?

### ISSUE THREAD

**Issue by brandonsturgeon** [ferraridavide/ChatGPTPowerToys#1]
Thanks for making this! It's just what I was looking for.

Would you be willing _(and would it be possible)_ to add a precompiled version to the Releases page, just to make it a little more accessible?

**Comment by ferraridavide** [comment]
Hi, thanks for the suggestion and sorry for the delay, i just published the compiled binaries for x64 and ARM64!

**Comment by brandonsturgeon** [comment]
Incredible, thanks so much!

**Comment by brandonsturgeon** [comment]
You may want to add something in the README about using the binaries from the latest release, too - I'm sure people would look for something like that right away (I did, at least) 👍

**Comment by ferraridavide** [comment]
Just did! Thanks!
