### ISSUE TITLE
After windows latest 22H Update - Plugin Fails to load

### ISSUE THREAD

**Issue by lankdaniel14** [ferraridavide/ChatGPTPowerToys#10]
Hello, the plugin won't load after windows update

Steps taken - 
1. Reinstall 
2. Powertoys Update
3. Reinstall powertoys

Thank you

**Comment by ferraridavide** [comment]
Hi, could you provide the version of PowerToys you are using?

**Comment by elixir7** [comment]
@ferraridavide 
Hijacking thread. Probably got the same issue. Update PowerToyz to **v0.75.1**
Note that the [installation folder](https://github.com/microsoft/PowerToys/blob/main/doc/thirdPartyRunPlugins.md#installing-and-upgrading-third-party-powertoys-run-plugins) seems to have changed for PowerToyz Run to: 

`%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins`

Getting the following "failed to load" error:
![image](https://github.com/ferraridavide/ChatGPTPowerToys/assets/12642818/6d18c94c-5dd2-4a19-bb9c-6471480f638e)

**Comment by ferraridavide** [comment]
Thanks @elixir7, will look into it

**Comment by lankdaniel14** [comment]
> Hi, could you provide the version of PowerToys you are using?

Its Version 0.75.1

**Comment by elixir7** [comment]
Tried this on another computer today with latest version (v0.75.1) and got the same problem.
Did you find a solution to this? @ferraridavide

**Comment by andremohrmann** [comment]
Same for me. Any updates on this? @ferraridavide

**Comment by ferraridavide** [comment]
@elixir7 @lankdaniel14 @andremohrmann @akamienski 
This should be fixed in the latest commit and released binaries
Let me know if any other problems arise
