### ISSUE TITLE
Doesn't open in ChatGPT PWA.

### ISSUE THREAD

**Issue by GollyJer** [ferraridavide/ChatGPTPowerToys#13]
I hoped this would open in the Edge Browser chatGPT PWA, but sadly, it does not.

"New" chatgpt uses the url `https://chatgpt.com` but it does not accept query parameters.
The `https://chat.openai.com` url still takes query parameters and redirects to chatgpt.com. 
That is really the trick of this plugin, which is cool.

PWAs can handle their own urls, but I can't find a way to add chat.openai.com as an additional handler. I don't think it's possible. ☹️

![image](https://github.com/user-attachments/assets/2326aaa5-1243-43dd-b1c4-f9f70357395a)

**Comment by martesi** [comment]
`https://chatgpt.com/?q=` seems to work. I'm using Microsoft Edge, installed ChatGPT manually as a PWA, and couldn't find link handling in App Settings.

**Comment by martesi** [comment]
Try this [version](https://github.com/martesi/ChatGPTPowerToys/releases/tag/v0.84.1) and see if this works for you.

**Comment by GollyJer** [comment]
Good find martesi. I thought maybe it would work, but it doesn't.

To enable link handling for pwa's in edge...
go to `edge://flags/#edge-webapp-link-handling` and enable it.

<img width="600" alt="adsoifj" src="https://github.com/user-attachments/assets/54900357-b732-4947-8b29-a36f790addd8">

Then you'll be able to turn on/off link handling in the app settings.
`edge://apps/`

<img width="450" alt="obdLuhEcvl" src="https://github.com/user-attachments/assets/d97a28ee-e486-4046-9e8e-6d50f594d8b6">

**Comment by ferraridavide** [comment]
Thanks guys, i merged @martesi's branch!

**Comment by GollyJer** [comment]
@ferraridavide Does it work for you? Even though I have everything set up it still doesn't. I don't think it's on your end, it just seems that Edge isn't actually handling the url via the PWA.

**Comment by ferraridavide** [comment]
The new domain works, which is the only thing that changes, PWA link handling is dependent on the browser, so we might have to wait for browsers to support it or enable the experimental flag

**Comment by martesi** [comment]
Link Handling works on my end. Every query would open a new PWA window.

**Comment by endrefasong** [comment]
Just adding some general praise for an active and awesome project 🥳

**Comment by AJolly** [comment]
Whats the benefit of the PWA approach vs say chrome.com --app=https://chat.openai.com ?

**Comment by GollyJer** [comment]
@AJolly Hey! Crazy to see an old biohacker in a random place like this...

PWA isn't massively different than using a Chrome shortcut like that. The main reason I use a PWA is I want all calls to chatgpt to open in the same window. You can register a PWA to handle links and file types.

**Comment by GollyJer** [comment]
Ha. It literally just launched today.

https://apps.microsoft.com/detail/9nt1r1c2hh7j

**Comment by skydiverrg** [comment]
I've the PWA installed but power toys run still opens Edge for the request.

**Comment by AKshayyyy-ak** [comment]
its not working now ?

**Comment by Kamiikaze** [comment]
I got the windows app too, but cant make it work that powerrun opens the search in the app
